name: Java CI with Gradle

on:
  push:
    branches: [ "develop" ]  # develop 브랜치에 푸시될 때 배포
  pull_request:
    branches: [ "develop" ]  # develop 브랜치에 대한 PR에 대해서도 실행

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true  # 서브모듈 초기화는 이곳에 위치해야 합니다.
        token: ${{ secrets.GIT_TOKEN }}

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582  # v4.0.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build

  deploy:
    if: github.ref == 'refs/heads/develop'  # develop 브랜치에 푸시될 때 배포
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # 서브모듈 초기화는 이곳에 위치해야 합니다.
          token: ${{ secrets.GIT_TOKEN }}
  
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
  
      - name: Deploy to EC2 using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}  # SSH 키
          port: 22
          script: |
            # 1. 기존 실행 중인 프로세스를 종료
            pkill -f 'java -jar clat-0.0.1-SNAPSHOT.jar' || true
            
            # 2. 기존 CLAT-SERVER 디렉토리 삭제
            rm -rf /home/ubuntu/CLAT-SERVER
            
            # 3. 최신 코드로 Git 클론 (서브모듈 포함)
            git clone --recurse-submodules --branch develop git@github.com:CLAT-Project/CLAT-SERVER.git /home/ubuntu/CLAT-SERVER
      
            # 4. 프로젝트 디렉토리로 이동
            cd /home/ubuntu/CLAT-SERVER
            
            # 5. Gradle 빌드 실행
            ./gradlew build
            
            # 6. 빌드된 파일이 있는 디렉토리로 이동
            cd build/libs
            
            # 7. 애플리케이션 실행 (백그라운드에서)
            nohup java -jar clat-0.0.1-SNAPSHOT.jar > /home/ubuntu/clat.log 2>&1 &
            
            # 8. 프로세스가 제대로 실행 중인지 확인
            ps aux | grep 'java -jar clat-0.0.1-SNAPSHOT.jar'











  
